version: '3'

services:
  # PHP 5.3 contains neither mbstring extension nor docker-php-ext-install script
  # Original Dockerfile can be found here https://github.com/docker-library/php/pull/20/files
  # Unfortunately it fails to build now because GPG signatures do not exist anymore
  # php-5.3: { build: { context: docker/php-5.x, args: { PHP_VERSION: 5.3   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-5.4: { build: { context: docker/php-5.x, args: { PHP_VERSION: 5.4   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-5.5: { build: { context: docker/php-5.x, args: { PHP_VERSION: 5.5   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-5.6: { build: { context: docker/php-5.x, args: { PHP_VERSION: 5.6   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-7.0: { build: { context: docker/php,     args: { PHP_VERSION: 7.0   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-7.1: { build: { context: docker/php,     args: { PHP_VERSION: 7.1.3 } }, volumes: ['.:/app'], working_dir: '/app' }
  php-7.2: { build: { context: docker/php,     args: { PHP_VERSION: 7.2   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-7.3: { build: { context: docker/php,     args: { PHP_VERSION: 7.3   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-7.4: { build: { context: docker/php,     args: { PHP_VERSION: 7.4   } }, volumes: ['.:/app'], working_dir: '/app' }
  php-8.0: { build: { context: docker/php,     args: { PHP_VERSION: rc    } }, volumes: ['.:/app'], working_dir: '/app' }
